---
# Source: oadp-argocd/templates/create_custom_sa.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: query-pods
  annotations:
    argocd.argoproj.io/sync-wave: "-2"
---
# Source: oadp-argocd/templates/create_custom_sa.yaml
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: pod-viewer-oadp
  annotations:
    argocd.argoproj.io/sync-wave: "-2"

rules:
- apiGroups: [""] # core API group
  resources: ["pods", "namespaces", "machines"]
  verbs: ["get", "watch", "list"]
- apiGroups: ["machine.openshift.io"] 
  resources: ["machines"]
  verbs: ["get", "watch", "list"]
---
# Source: oadp-argocd/templates/create_custom_sa.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: pod-viewer-bind-oadp
  annotations:
    argocd.argoproj.io/sync-wave: "-2"
subjects:
  - kind: ServiceAccount
    name: query-pods
    namespace: openshift-storage
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: pod-viewer-oadp
