---
# Source: oadp-argocd/templates/oadp-operatorgroup.yaml
apiVersion: operators.coreos.com/v1
kind: OperatorGroup
metadata:
  name: openshift-adp-hvhxt
  namespace: openshift-adp
spec:
  targetNamespaces:
  - openshift-adp
